compressionLevel: 0
enableGlobalCache: true

enableScripts: false
nmMode: classic

nodeLinker: node-modules
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

preferAggregateCacheInfo: true

yarnPath: .yarn/releases/yarn-3.6.1.cjs
logFilters:
  - level: discard
    pattern: 'fsevents@*/* The * architecture is incompatible with this module, link skipped.'
  - level: discard
    pattern: "@automattic/wpcom-editing-toolkit@workspace:apps/editing-toolkit provides +(react|react-dom) (*) with version 18.2.0, which doesn't satisfy what @automattic/newspack-blocks and some of its descendants request"
  - level: discard
    pattern: "**@workspace:+(client|*/*|.) provides +(react|react-dom) (*) with version 18.2.0, which doesn't satisfy what +(@wordpress/*|@types/wordpress__*) and some of its descendants request"
  - level: discard
    pattern: "calypso@workspace:client provides +(react|react-dom) (*) with version 18.2.0, which doesn't satisfy what reakit and some of its descendants request"
  - level: discard
    pattern: "calypso@workspace:client provides +(react|react-dom) (*) with version 18.2.0, which doesn't satisfy what @automattic/block-renderer and some of its descendants request"
  - level: discard
    pattern: "calypso@workspace:client provides react (*) with version 18.2.0, which doesn't satisfy what react-day-picker requests"

packageExtensions:
  '@automattic/newspack-blocks@*':
    peerDependencies:
      moment: '*'
      react: '*'
      react-dom: '*'
  '@signal-noise/stylelint-scales@2.0.3':
    peerDependencies:
      postcss: '*'
  '@types/wordpress__components@23.0.1':
    peerDependencies:
      react: '*'
  '@types/wordpress__plugins@3.0.0':
    peerDependencies:
      react: '*'
  '@wordpress/data-controls@2.23.0':
    peerDependencies:
      react: '*'
  '@wordpress/notices@3.23.0':
    peerDependencies:
      react: '*'
  '@wordpress/stylelint-config@21.6.0':
    peerDependencies:
      postcss: '*'
  fake-indexeddb@3.1.7:
    peerDependencies:
      core-js-bundle: '*'
      regenerator-runtime: '*'
  newspack-components@2.1.0:
    peerDependencies:
      moment: '*'
      react: '*'
      react-dom: '*'
  reakit-warning@0.6.2:
    peerDependencies:
      react-dom: '*'
  realistic-structured-clone@2.0.2:
    peerDependencies:
      core-js-bundle: '*'
      regenerator-runtime: '*'
  stylelint-config-recommended-scss@5.0.2:
    peerDependencies:
      postcss: '*'
  typeson-registry@1.0.0-alpha.35:
    peerDependencies:
      core-js-bundle: '*'
      regenerator-runtime: '*'
